const actions = {
    UPLOAD_FILE: "UPLOAD_FILE",
    VIEW_REPORT: "VIEW_REPORT",
    MARK_ATTENDANCE: "MARK_ATTENDANCE",
    VIEW_TIMETABLE: "VIEW_TIMETABLE",
    VIEW_ADVISOR_VIEW: "VIEW_ADVISOR_VIEW",
    EDIT_MODULE: "EDIT_MODULE",
    EDIT_COURSE: "EDIT_COURSE",
    EDIT_SESSION: "EDIT_SESSION",
    ADD_STUDENT_TO_SESSION: "ADD_STUDENT_TO_SESSION",
    RETURN_HOME: "RETURN_HOME"
  };

  const roles = {
    STUDENT: "1",
    ACADEMIC_ADVISOR: "2",
    TUTOR: "3",
    MODULE_LEADER: "4",
    COURSE_LEADER: "5",
  };

  export { actions, roles };